services:
  db:
    image: &db-image postgres:17-alpine3.20
    restart: unless-stopped
    container_name: ka-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ka-db-network
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 5s
      timeout: 10s
      retries: 20

  db-test:
    image: *db-image
    container_name: ka-db-test
    command:
      postgres -c 'max_connections=250' -c 'max_locks_per_transaction=128'
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_ka_db
      POSTGRES_USER: test_ka_user
      POSTGRES_PASSWORD: test_ka_user_password
    volumes:
      - ./docker/postgres/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql:ro
    networks:
      - ka-db-network

  app: &app
    build:
      context: ./
      dockerfile: docker/php/Dockerfile-dev
    restart: unless-stopped
    container_name: ka-app
    environment:
      COMMAND: php artisan octane:frankenphp --host=localhost --port=443 --https --http-redirect --watch
      PROCESS: app
      XDEBUG_MODE: debug,coverage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/var/www
      - caddy_data:/data
      - caddy_config:/config
      - ka_app_composer_data:/.composer
    ports:
      - '8081:80'
      - '8443:443'
      - '8443:443/udp'
      - '5173:5173'
      - '9003:9003'
    networks:
      - ka-db-network
      - ka-redis-network
    healthcheck:
      test: curl -sk https://localhost/up >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 20
    stop_signal: SIGINT
    stop_grace_period: 10s

  workers:
    <<: *app
    container_name: ka-worker
    environment:
      COMMAND: php artisan queue:work --sleep=3 --tries=3 --timeout=60
      PROCESS: worker
    ports: []
    stop_grace_period: 30s
    networks:
      - ka-db-network
      - ka-redis-network

  schedule:
    <<: *app
    container_name: ka-schedule
    environment:
      COMMAND: supercronic -quiet /var/www/docker/schedule/crontab
      PROCESS: schedule
    networks:
      - ka-db-network
      - ka-redis-network
    ports: []
    healthcheck:
      test: supercronic -test /var/www/docker/schedule/crontab | grep -q
        'is valid' # TODO try spatie LARAVEL-HEALTH
      interval: 5s
      timeout: 10s
      retries: 2

  websockets:
    <<: *app
    container_name: ka-websockets
    environment:
      COMMAND:
        php artisan reverb:start --host="0.0.0.0" --port=8080
        --hostname="localhost" --debug
      PROCESS: reverb
    ports:
      - '8080:8080'
    networks:
      - ka-db-network
      - ka-redis-network

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    container_name: ka-redis
    command:
      - 'redis-server'
      - '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis_data:/data
    networks:
      - ka-redis-network
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 20

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - ka-db-network

volumes:
  db_data:
    driver: local
    name: ka_db_data
  redis_data:
    driver: local
    name: ka_redis_data
  caddy_data:
    driver: local
    name: ka_caddy_data
  caddy_config:
    driver: local
    name: ka_caddy_config
  ka_app_composer_data:
    driver: local
    name: ka_app_composer_data

networks:
  ka-db-network:
    driver: bridge
    name: ka-db-network
  ka-redis-network:
    driver: bridge
    name: ka-redis-network
