/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "dashboard": [],
    "login": [],
    "register": [],
    "oauth.redirect": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "oauth.callback": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "logout": [],
    "settings": [],
    "settings.profile": [],
    "settings.password": [],
    "settings.account": [],
    "settings.oauth.link": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "settings.oauth.unlink": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "addresses.index": [],
    "addresses.create": [],
    "addresses.store": [],
    "addresses.edit": [
        {
            "name": "address",
            "required": true
        }
    ],
    "addresses.update": [
        {
            "name": "address",
            "required": true
        }
    ],
    "addresses.destroy": [
        {
            "name": "address",
            "required": true
        }
    ],
    "providers.index": [],
    "providers.create": [],
    "providers.store": [],
    "providers.edit": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "providers.update": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "providers.destroy": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "meters.index": [],
    "meters.create": [],
    "meters.store": [],
    "meters.edit": [
        {
            "name": "meter",
            "required": true
        }
    ],
    "meters.update": [
        {
            "name": "meter",
            "required": true
        }
    ],
    "meters.destroy": [
        {
            "name": "meter",
            "required": true
        }
    ],
    "meters.photo": [
        {
            "name": "meter",
            "required": true
        }
    ],
    "readings.index": [],
    "readings.create": [],
    "readings.store": [],
    "readings.destroy": [
        {
            "name": "reading",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
